### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by Prokac** [jwdeveloper/TikTok-Live-Java#1]
Code used from the example

sie 23, 2023 3:11:31 PM io.github.jwdeveloper.tiktok.TikTokLiveClient tryConnect
INFO: Connecting
sie 23, 2023 3:11:31 PM io.github.jwdeveloper.tiktok.TikTokLiveClient setState
INFO: TikTokLive client state: CONNECTING
sie 23, 2023 3:11:31 PM io.github.jwdeveloper.tiktok.http.TikTokApiService fetchRoomId
INFO: Fetching room ID
sie 23, 2023 3:11:34 PM io.github.jwdeveloper.tiktok.http.TikTokApiService fetchRoomId
INFO: RoomID -> 7270503304264682273
sie 23, 2023 3:11:34 PM io.github.jwdeveloper.tiktok.http.TikTokApiService fetchRoomInfo
INFO: Fetch RoomInfo
sie 23, 2023 3:11:35 PM io.github.jwdeveloper.tiktok.http.TikTokApiService fetchRoomInfo
INFO: RoomInfo status -> 2
sie 23, 2023 3:11:35 PM io.github.jwdeveloper.tiktok.http.TikTokApiService fetchClientData
INFO: Fetch ClientData
io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Failed to fetch client data
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:98)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:76)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:42)
	at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndRun(TikTokLiveClientBuilder.java:90)
	at pl.prokac.tiktok.TikTok.main(TikTok.java:29)
Caused by: io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Unable to deserialize message: im/fetch/
	at io.github.jwdeveloper.tiktok.http.TikTokHttpApiClient.GetDeserializedMessage(TikTokHttpApiClient.java:48)
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:91)
	... 4 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1259)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:910)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:513)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:490)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:603)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:303)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:833)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:517)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:332)
	at io.github.jwdeveloper.tiktok.messages.WebcastResponse.<init>(WebcastResponse.java:123)
	at io.github.jwdeveloper.tiktok.messages.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:3249)
	at io.github.jwdeveloper.tiktok.messages.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:3243)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.github.jwdeveloper.tiktok.messages.WebcastResponse.parseFrom(WebcastResponse.java:1999)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpApiClient.GetDeserializedMessage(TikTokHttpApiClient.java:44)
	... 5 more
sie 23, 2023 3:11:37 PM io.github.jwdeveloper.tiktok.TikTokLiveClient setState
INFO: TikTokLive client state: DISCONNECTED

**Comment by jwdeveloper** [comment]
Hi, are you using latest version? `0.0.11-Release`

**Comment by jwdeveloper** [comment]
Try out new version `0.0.12-Release` I've fixed few bugs so it should be working. Also update your example project because there was some changes in events
